### ISSUE TITLE
Recent Update made the train no longer able to depart

### ISSUE THREAD

**Issue by flyrobot27** [Gregory365/TPF2-Timetables#58]
I am having issue with the recent "force depart" update. The trains no longer departs the station and causing massive train jam. This happens on both the lines set for auto unbunch and a timetable. The save game was running an older version of this mod. I still have the save game and it will be great if you can look into this.

Steps to reproduce:

Create a game with older version of this mod (before the force departure update).

Create a line. Set a auto unbunch or something. Let the game to run for a while.

Update the save game with the current version of this mod.

You will notice that trains will randomly stopped departing, or the trains will depart immediately.

**Comment by Gregory365** [comment]
Unfortunately, I can't reproduce this issue with the information provided. Could you upload the sav.lua file for that save?

**Comment by flyrobot27** [comment]
For sure, here is the save.lua file:

[autosave_Linear Island_2192-10-14.sav.lua.zip](https://github.com/Gregory365/TPF2-Timetables/files/13467989/autosave_Linear.Island_2192-10-14.sav.lua.zip)

If you need other files please let me know

**Comment by flyrobot27** [comment]
Have you managed to make any progress with this issue?

**Comment by Gregory365** [comment]
I still haven't been able to reproduce this using the steps provided. One issue I did find was that only Unbunch & AutoUnbunch using multiple platforms doesn't work as expected, but I was also able to reproduce this issue in v1.3.2 as well. Let me know if you think this is the issue you are facing.

Having looked at the sav.lua, it looks like this issue may be related to #55, which has been fixed in the develop branch.
Could you use the develop branch of this mod to see if that solves the issue?

If not, you will need to be more specific about "randomly departing". Give one specific scenario with the timetable slot (or unbunch time or margin time), the time you expect the vehicle to depart and the actual arrival time & actual departure time.

**Comment by flyrobot27** [comment]
Okay, it seems that the developer version seems to have fixed this issue. I will still need to run the game for a couple of hours to confirm it is fine. Thanks for the update

**Comment by flyrobot27** [comment]
Hi, sorry but it seems that the problem still exists. I checked the log and I still get a lot of "Timetables failed to resume dead coroutine". The error is thrown at line 657 of the timetable.lua file: attempt to index "VehiclesWaiting (A Nil value)". 

I am on the development build, pulled around 2 days ago. This is the full save lua file:
[Fail.sav.zip](https://github.com/Gregory365/TPF2-Timetables/files/13710643/Fail.sav.zip)

**Comment by Gregory365** [comment]
Thanks for the report. I have pushed a fix to the develop branch.
That issue would have been quite rare, so there is probably still an underlying issue. Please continue to report any other errors you get from the log.

**Comment by Gregory365** [comment]
Fixed in v1.3.5
